### ISSUE TITLE
AVAX sync

### ISSUE THREAD

**Issue by pom11** [blocknetdx/documentation#59]
document steps for `exrproxy-env` AVAX syncing using a simple input file like 
```yaml
- j2template: dockercompose.j2
  name: dockercompose
  daemons:  
    - name: SNODE 
      image: blocknetdx/servicenode:latest 
      config_mount_dir: /snode 
      data_mount_dir: /snode
    - name: XR_PROXY 
      image: blocknetdx/exrproxy:0.9.0 
      config_mount_dir: /snode/xr_proxy/config 
      nginx_mount_dir: /snode/xr_proxy/nginx  
    - name: AVAX 
      image: avaplatform/avalanchego:v1.7.2
      data_mount_dir: /snode
```
